//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubwayNavigation.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubwayNavigation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;subway&gt;
        ///	&lt;stations&gt;
        ///		&lt;station id=&quot;0&quot; line=&quot;green&quot;&gt;
        ///			&lt;nameRu&gt;Красный Хутор&lt;/nameRu&gt;
        ///			&lt;nameEng&gt;Chervony Khutir&lt;/nameEng&gt;
        ///			&lt;railways&gt;1&lt;/railways&gt;
        ///		&lt;/station&gt;
        ///		&lt;station id=&quot;1&quot; line=&quot;green&quot;&gt;
        ///			&lt;nameRu&gt;Бориспольская&lt;/nameRu&gt;
        ///			&lt;nameEng&gt;Boryspilska&lt;/nameEng&gt;
        ///			&lt;railways&gt;0, 2&lt;/railways&gt;
        ///		&lt;/station&gt;
        ///		&lt;station id=&quot;2&quot; line=&quot;green&quot;&gt;
        ///			&lt;nameRu&gt;Вырлица&lt;/nameRu&gt;
        ///			&lt;nameEng&gt;Vyrlytsia&lt;/nameEng&gt;
        ///			&lt;railways&gt;1, 3 &lt;/railways&gt;
        ///		&lt;/station&gt;
        ///		&lt;station id= [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string graphdataxml {
            get {
                return ResourceManager.GetString("graphdataxml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
